name: catalog_all_modules.deployment

system: Catalog.system

# vehicle specific parameters, such as sensor calibration, vehicle dimensions
vehicle_parameters: []

# environment specific parameters, such as map data
environment_parameters: []
