name: universe_perception_clr_centerpoint_serial.deployment

system: CameraLidarRadarCenterpointSerial.system

global_parameters:
  - name: vehicle_id
    value: virtual_vehicle_01
  - name: data_path
    value: $(env HOME)/autoware_data

environment_parameters:
  - name: lanelet2_map_file
    value: lanelet2_map.osm
  - name: pointcloud_map_file
    value: pointcloud_map.pcd
